version: "3.9"

name: sanime2

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_ENDPOINT: http://localhost:4000
    depends_on:
      backend:
        condition: service_started
    ports:
      - published: 8080
        target: 8080

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      REDIS_URL: redis://redis:6379
      ANNICT_TOKEN: $ANNICT_TOKEN
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
